//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.11 at 08:31:05 PM EDT 
//


package umich.ms.fileio.filetypes.pepxml.jaxb.primitive;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the umich.ms.fileio.filetypes.pepxml.jaxb.primitive package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: umich.ms.fileio.filetypes.pepxml.jaxb.primitive
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AsapratioLcLightpeak }
     * 
     */
    public AsapratioLcLightpeak createAsapratioLcLightpeak() {
        return new AsapratioLcLightpeak();
    }

    /**
     * Create an instance of {@link AsapratioLcHeavypeak }
     * 
     */
    public AsapratioLcHeavypeak createAsapratioLcHeavypeak() {
        return new AsapratioLcHeavypeak();
    }

    /**
     * Create an instance of {@link XpressratioTimestamp }
     * 
     */
    public XpressratioTimestamp createXpressratioTimestamp() {
        return new XpressratioTimestamp();
    }

    /**
     * Create an instance of {@link PeptideprophetResult }
     * 
     */
    public PeptideprophetResult createPeptideprophetResult() {
        return new PeptideprophetResult();
    }

    /**
     * Create an instance of {@link SearchScoreSummary }
     * 
     */
    public SearchScoreSummary createSearchScoreSummary() {
        return new SearchScoreSummary();
    }

    /**
     * Create an instance of {@link AsapratioSummary }
     * 
     */
    public AsapratioSummary createAsapratioSummary() {
        return new AsapratioSummary();
    }

    /**
     * Create an instance of {@link LibraResult }
     * 
     */
    public LibraResult createLibraResult() {
        return new LibraResult();
    }

    /**
     * Create an instance of {@link Intensity }
     * 
     */
    public Intensity createIntensity() {
        return new Intensity();
    }

    /**
     * Create an instance of {@link XpressratioResult }
     * 
     */
    public XpressratioResult createXpressratioResult() {
        return new XpressratioResult();
    }

    /**
     * Create an instance of {@link InterprophetSummary }
     * 
     */
    public InterprophetSummary createInterprophetSummary() {
        return new InterprophetSummary();
    }

    /**
     * Create an instance of {@link InputFileType }
     * 
     */
    public InputFileType createInputFileType() {
        return new InputFileType();
    }

    /**
     * Create an instance of {@link RocErrorDataType }
     * 
     */
    public RocErrorDataType createRocErrorDataType() {
        return new RocErrorDataType();
    }

    /**
     * Create an instance of {@link MixtureModelType }
     * 
     */
    public MixtureModelType createMixtureModelType() {
        return new MixtureModelType();
    }

    /**
     * Create an instance of {@link MsmsPipelineAnalysis }
     * 
     */
    public MsmsPipelineAnalysis createMsmsPipelineAnalysis() {
        return new MsmsPipelineAnalysis();
    }

    /**
     * Create an instance of {@link AnalysisSummary }
     * 
     */
    public AnalysisSummary createAnalysisSummary() {
        return new AnalysisSummary();
    }

    /**
     * Create an instance of {@link DatasetDerivation }
     * 
     */
    public DatasetDerivation createDatasetDerivation() {
        return new DatasetDerivation();
    }

    /**
     * Create an instance of {@link MsmsRunSummary }
     * 
     */
    public MsmsRunSummary createMsmsRunSummary() {
        return new MsmsRunSummary();
    }

    /**
     * Create an instance of {@link AsapratioContribution }
     * 
     */
    public AsapratioContribution createAsapratioContribution() {
        return new AsapratioContribution();
    }

    /**
     * Create an instance of {@link AsapratioTimestamp }
     * 
     */
    public AsapratioTimestamp createAsapratioTimestamp() {
        return new AsapratioTimestamp();
    }

    /**
     * Create an instance of {@link InteractSummary }
     * 
     */
    public InteractSummary createInteractSummary() {
        return new InteractSummary();
    }

    /**
     * Create an instance of {@link LibraSummary }
     * 
     */
    public LibraSummary createLibraSummary() {
        return new LibraSummary();
    }

    /**
     * Create an instance of {@link FragmentMasses }
     * 
     */
    public FragmentMasses createFragmentMasses() {
        return new FragmentMasses();
    }

    /**
     * Create an instance of {@link IsotopicContributions }
     * 
     */
    public IsotopicContributions createIsotopicContributions() {
        return new IsotopicContributions();
    }

    /**
     * Create an instance of {@link PeptideprophetSummary }
     * 
     */
    public PeptideprophetSummary createPeptideprophetSummary() {
        return new PeptideprophetSummary();
    }

    /**
     * Create an instance of {@link DistributionPoint }
     * 
     */
    public DistributionPoint createDistributionPoint() {
        return new DistributionPoint();
    }

    /**
     * Create an instance of {@link MixtureModelling }
     * 
     */
    public MixtureModelling createMixtureModelling() {
        return new MixtureModelling();
    }

    /**
     * Create an instance of {@link AsapratioPeptideData }
     * 
     */
    public AsapratioPeptideData createAsapratioPeptideData() {
        return new AsapratioPeptideData();
    }

    /**
     * Create an instance of {@link DatabaseRefreshTimestamp }
     * 
     */
    public DatabaseRefreshTimestamp createDatabaseRefreshTimestamp() {
        return new DatabaseRefreshTimestamp();
    }

    /**
     * Create an instance of {@link XpressratioSummary }
     * 
     */
    public XpressratioSummary createXpressratioSummary() {
        return new XpressratioSummary();
    }

    /**
     * Create an instance of {@link InterprophetResult }
     * 
     */
    public InterprophetResult createInterprophetResult() {
        return new InterprophetResult();
    }

    /**
     * Create an instance of {@link SearchScoreSummaryIProphet }
     * 
     */
    public SearchScoreSummaryIProphet createSearchScoreSummaryIProphet() {
        return new SearchScoreSummaryIProphet();
    }

    /**
     * Create an instance of {@link AsapratioResult }
     * 
     */
    public AsapratioResult createAsapratioResult() {
        return new AsapratioResult();
    }

    /**
     * Create an instance of {@link NameValueType }
     * 
     */
    public NameValueType createNameValueType() {
        return new NameValueType();
    }

    /**
     * Create an instance of {@link MixturemodelDistribution }
     * 
     */
    public MixturemodelDistribution createMixturemodelDistribution() {
        return new MixturemodelDistribution();
    }

    /**
     * Create an instance of {@link Mixturemodel }
     * 
     */
    public Mixturemodel createMixturemodel() {
        return new Mixturemodel();
    }

    /**
     * Create an instance of {@link Point }
     * 
     */
    public Point createPoint() {
        return new Point();
    }

    /**
     * Create an instance of {@link PosmodelDistribution }
     * 
     */
    public PosmodelDistribution createPosmodelDistribution() {
        return new PosmodelDistribution();
    }

    /**
     * Create an instance of {@link NegmodelDistribution }
     * 
     */
    public NegmodelDistribution createNegmodelDistribution() {
        return new NegmodelDistribution();
    }

    /**
     * Create an instance of {@link ContributingChannel }
     * 
     */
    public ContributingChannel createContributingChannel() {
        return new ContributingChannel();
    }

    /**
     * Create an instance of {@link AffectedChannel }
     * 
     */
    public AffectedChannel createAffectedChannel() {
        return new AffectedChannel();
    }

    /**
     * Create an instance of {@link SampleEnzyme }
     * 
     */
    public SampleEnzyme createSampleEnzyme() {
        return new SampleEnzyme();
    }

    /**
     * Create an instance of {@link SearchSummary }
     * 
     */
    public SearchSummary createSearchSummary() {
        return new SearchSummary();
    }

    /**
     * Create an instance of {@link AnalysisTimestamp }
     * 
     */
    public AnalysisTimestamp createAnalysisTimestamp() {
        return new AnalysisTimestamp();
    }

    /**
     * Create an instance of {@link SpectrumQuery }
     * 
     */
    public SpectrumQuery createSpectrumQuery() {
        return new SpectrumQuery();
    }

    /**
     * Create an instance of {@link SearchResult }
     * 
     */
    public SearchResult createSearchResult() {
        return new SearchResult();
    }

    /**
     * Create an instance of {@link SearchHit }
     * 
     */
    public SearchHit createSearchHit() {
        return new SearchHit();
    }

    /**
     * Create an instance of {@link AlternativeProtein }
     * 
     */
    public AlternativeProtein createAlternativeProtein() {
        return new AlternativeProtein();
    }

    /**
     * Create an instance of {@link ModificationInfo }
     * 
     */
    public ModificationInfo createModificationInfo() {
        return new ModificationInfo();
    }

    /**
     * Create an instance of {@link AnalysisResult }
     * 
     */
    public AnalysisResult createAnalysisResult() {
        return new AnalysisResult();
    }

    /**
     * Create an instance of {@link ModAminoacidMass }
     * 
     */
    public ModAminoacidMass createModAminoacidMass() {
        return new ModAminoacidMass();
    }

    /**
     * Create an instance of {@link SearchDatabase }
     * 
     */
    public SearchDatabase createSearchDatabase() {
        return new SearchDatabase();
    }

    /**
     * Create an instance of {@link EnzymaticSearchConstraint }
     * 
     */
    public EnzymaticSearchConstraint createEnzymaticSearchConstraint() {
        return new EnzymaticSearchConstraint();
    }

    /**
     * Create an instance of {@link SequenceSearchConstraint }
     * 
     */
    public SequenceSearchConstraint createSequenceSearchConstraint() {
        return new SequenceSearchConstraint();
    }

    /**
     * Create an instance of {@link AminoacidModification }
     * 
     */
    public AminoacidModification createAminoacidModification() {
        return new AminoacidModification();
    }

    /**
     * Create an instance of {@link TerminalModification }
     * 
     */
    public TerminalModification createTerminalModification() {
        return new TerminalModification();
    }

    /**
     * Create an instance of {@link Specificity }
     * 
     */
    public Specificity createSpecificity() {
        return new Specificity();
    }

    /**
     * Create an instance of {@link DataFilter }
     * 
     */
    public DataFilter createDataFilter() {
        return new DataFilter();
    }

    /**
     * Create an instance of {@link MixtureModelPoint }
     * 
     */
    public MixtureModelPoint createMixtureModelPoint() {
        return new MixtureModelPoint();
    }

    /**
     * Create an instance of {@link RocDataPoint }
     * 
     */
    public RocDataPoint createRocDataPoint() {
        return new RocDataPoint();
    }

    /**
     * Create an instance of {@link ErrorPoint }
     * 
     */
    public ErrorPoint createErrorPoint() {
        return new ErrorPoint();
    }

}
