//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.12 at 01:56:05 PM EDT 
//


package umich.ms.fileio.filetypes.pepxml.jaxb.primitive;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="pos_dens" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="neg_dens" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class Point {

    @XmlAttribute(name = "value")
    protected float value;
    @XmlAttribute(name = "pos_dens")
    protected float posDens;
    @XmlAttribute(name = "neg_dens")
    protected float negDens;

    /**
     * Gets the value of the value property.
     * 
     */
    public float getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(float value) {
        this.value = value;
    }

    /**
     * Gets the value of the posDens property.
     * 
     */
    public float getPosDens() {
        return posDens;
    }

    /**
     * Sets the value of the posDens property.
     * 
     */
    public void setPosDens(float value) {
        this.posDens = value;
    }

    /**
     * Gets the value of the negDens property.
     * 
     */
    public float getNegDens() {
        return negDens;
    }

    /**
     * Sets the value of the negDens property.
     * 
     */
    public void setNegDens(float value) {
        this.negDens = value;
    }

}
