//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 02:29:00 PM EDT 
//


package umich.ms.fileio.filetypes.protxml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="binary_ref_files" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="min_peptide_probability" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="min_peptide_weight" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="min_protein_probability" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="reference_isotope" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ASAP_prot_analysis_summary")
public class ASAPProtAnalysisSummary {

    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "binary_ref_files")
    protected String binaryRefFiles;
    @XmlAttribute(name = "min_peptide_probability", required = true)
    @XmlJavaTypeAdapter(Adapter4 .class)
    @XmlSchemaType(name = "double")
    protected Double minPeptideProbability;
    @XmlAttribute(name = "min_peptide_weight", required = true)
    @XmlJavaTypeAdapter(Adapter4 .class)
    @XmlSchemaType(name = "double")
    protected Double minPeptideWeight;
    @XmlAttribute(name = "min_protein_probability", required = true)
    @XmlJavaTypeAdapter(Adapter4 .class)
    @XmlSchemaType(name = "double")
    protected Double minProteinProbability;
    @XmlAttribute(name = "reference_isotope")
    protected String referenceIsotope;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the binaryRefFiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinaryRefFiles() {
        return binaryRefFiles;
    }

    /**
     * Sets the value of the binaryRefFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinaryRefFiles(String value) {
        this.binaryRefFiles = value;
    }

    /**
     * Gets the value of the minPeptideProbability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getMinPeptideProbability() {
        return minPeptideProbability;
    }

    /**
     * Sets the value of the minPeptideProbability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinPeptideProbability(Double value) {
        this.minPeptideProbability = value;
    }

    /**
     * Gets the value of the minPeptideWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getMinPeptideWeight() {
        return minPeptideWeight;
    }

    /**
     * Sets the value of the minPeptideWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinPeptideWeight(Double value) {
        this.minPeptideWeight = value;
    }

    /**
     * Gets the value of the minProteinProbability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Double getMinProteinProbability() {
        return minProteinProbability;
    }

    /**
     * Sets the value of the minProteinProbability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinProteinProbability(Double value) {
        this.minProteinProbability = value;
    }

    /**
     * Gets the value of the referenceIsotope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceIsotope() {
        return referenceIsotope;
    }

    /**
     * Sets the value of the referenceIsotope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceIsotope(String value) {
        this.referenceIsotope = value;
    }

}
