//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 02:29:00 PM EDT 
//


package umich.ms.fileio.filetypes.protxml.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fragment_masses" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="channel" use="required" type="{http://regis-web.systemsbiology.net/protXML}positiveInt" />
 *                 &lt;attribute name="mz" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="isotopic_contributions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="contributing_channel" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="affected_channel" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="channel" use="required" type="{http://regis-web.systemsbiology.net/protXML}positiveInt" />
 *                                     &lt;attribute name="correction" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="channel" use="required" type="{http://regis-web.systemsbiology.net/protXML}positiveInt" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="mass_tolerance" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="centroiding_preference" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="normalization" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="output_type" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="channel_code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="min_pep_prob" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="min_pep_wt" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="min_prot_prob" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fragmentMasses",
    "isotopicContributions"
})
@XmlRootElement(name = "libra_summary")
public class LibraSummary {

    @XmlElement(name = "fragment_masses", required = true)
    protected List<LibraSummary.FragmentMasses> fragmentMasses;
    @XmlElement(name = "isotopic_contributions")
    protected LibraSummary.IsotopicContributions isotopicContributions;
    @XmlAttribute(name = "mass_tolerance", required = true)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "float")
    protected Float massTolerance;
    @XmlAttribute(name = "centroiding_preference", required = true)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "int")
    protected Integer centroidingPreference;
    @XmlAttribute(name = "normalization", required = true)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "int")
    protected Integer normalization;
    @XmlAttribute(name = "output_type", required = true)
    @XmlJavaTypeAdapter(Adapter3 .class)
    @XmlSchemaType(name = "int")
    protected Integer outputType;
    @XmlAttribute(name = "channel_code")
    protected String channelCode;
    @XmlAttribute(name = "min_pep_prob", required = true)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "float")
    protected Float minPepProb;
    @XmlAttribute(name = "min_pep_wt", required = true)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "float")
    protected Float minPepWt;
    @XmlAttribute(name = "min_prot_prob", required = true)
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "float")
    protected Float minProtProb;

    /**
     * Gets the value of the fragmentMasses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fragmentMasses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFragmentMasses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LibraSummary.FragmentMasses }
     * 
     * 
     */
    public List<LibraSummary.FragmentMasses> getFragmentMasses() {
        if (fragmentMasses == null) {
            fragmentMasses = new ArrayList<LibraSummary.FragmentMasses>();
        }
        return this.fragmentMasses;
    }

    /**
     * Gets the value of the isotopicContributions property.
     * 
     * @return
     *     possible object is
     *     {@link LibraSummary.IsotopicContributions }
     *     
     */
    public LibraSummary.IsotopicContributions getIsotopicContributions() {
        return isotopicContributions;
    }

    /**
     * Sets the value of the isotopicContributions property.
     * 
     * @param value
     *     allowed object is
     *     {@link LibraSummary.IsotopicContributions }
     *     
     */
    public void setIsotopicContributions(LibraSummary.IsotopicContributions value) {
        this.isotopicContributions = value;
    }

    /**
     * Gets the value of the massTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Float getMassTolerance() {
        return massTolerance;
    }

    /**
     * Sets the value of the massTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMassTolerance(Float value) {
        this.massTolerance = value;
    }

    /**
     * Gets the value of the centroidingPreference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getCentroidingPreference() {
        return centroidingPreference;
    }

    /**
     * Sets the value of the centroidingPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCentroidingPreference(Integer value) {
        this.centroidingPreference = value;
    }

    /**
     * Gets the value of the normalization property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getNormalization() {
        return normalization;
    }

    /**
     * Sets the value of the normalization property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalization(Integer value) {
        this.normalization = value;
    }

    /**
     * Gets the value of the outputType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Integer getOutputType() {
        return outputType;
    }

    /**
     * Sets the value of the outputType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputType(Integer value) {
        this.outputType = value;
    }

    /**
     * Gets the value of the channelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * Sets the value of the channelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelCode(String value) {
        this.channelCode = value;
    }

    /**
     * Gets the value of the minPepProb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Float getMinPepProb() {
        return minPepProb;
    }

    /**
     * Sets the value of the minPepProb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinPepProb(Float value) {
        this.minPepProb = value;
    }

    /**
     * Gets the value of the minPepWt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Float getMinPepWt() {
        return minPepWt;
    }

    /**
     * Sets the value of the minPepWt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinPepWt(Float value) {
        this.minPepWt = value;
    }

    /**
     * Gets the value of the minProtProb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Float getMinProtProb() {
        return minProtProb;
    }

    /**
     * Sets the value of the minProtProb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinProtProb(Float value) {
        this.minProtProb = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="channel" use="required" type="{http://regis-web.systemsbiology.net/protXML}positiveInt" />
     *       &lt;attribute name="mz" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FragmentMasses {

        @XmlAttribute(name = "channel", required = true)
        protected long channel;
        @XmlAttribute(name = "mz", required = true)
        @XmlJavaTypeAdapter(Adapter2 .class)
        @XmlSchemaType(name = "float")
        protected Float mz;

        /**
         * Gets the value of the channel property.
         * 
         */
        public long getChannel() {
            return channel;
        }

        /**
         * Sets the value of the channel property.
         * 
         */
        public void setChannel(long value) {
            this.channel = value;
        }

        /**
         * Gets the value of the mz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public Float getMz() {
            return mz;
        }

        /**
         * Sets the value of the mz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMz(Float value) {
            this.mz = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="contributing_channel" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="affected_channel" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="channel" use="required" type="{http://regis-web.systemsbiology.net/protXML}positiveInt" />
     *                           &lt;attribute name="correction" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="channel" use="required" type="{http://regis-web.systemsbiology.net/protXML}positiveInt" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contributingChannel"
    })
    public static class IsotopicContributions {

        @XmlElement(name = "contributing_channel", required = true)
        protected List<LibraSummary.IsotopicContributions.ContributingChannel> contributingChannel;

        /**
         * Gets the value of the contributingChannel property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contributingChannel property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContributingChannel().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LibraSummary.IsotopicContributions.ContributingChannel }
         * 
         * 
         */
        public List<LibraSummary.IsotopicContributions.ContributingChannel> getContributingChannel() {
            if (contributingChannel == null) {
                contributingChannel = new ArrayList<LibraSummary.IsotopicContributions.ContributingChannel>();
            }
            return this.contributingChannel;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="affected_channel" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="channel" use="required" type="{http://regis-web.systemsbiology.net/protXML}positiveInt" />
         *                 &lt;attribute name="correction" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="channel" use="required" type="{http://regis-web.systemsbiology.net/protXML}positiveInt" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "affectedChannel"
        })
        public static class ContributingChannel {

            @XmlElement(name = "affected_channel", required = true)
            protected List<LibraSummary.IsotopicContributions.ContributingChannel.AffectedChannel> affectedChannel;
            @XmlAttribute(name = "channel", required = true)
            protected long channel;

            /**
             * Gets the value of the affectedChannel property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the affectedChannel property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAffectedChannel().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link LibraSummary.IsotopicContributions.ContributingChannel.AffectedChannel }
             * 
             * 
             */
            public List<LibraSummary.IsotopicContributions.ContributingChannel.AffectedChannel> getAffectedChannel() {
                if (affectedChannel == null) {
                    affectedChannel = new ArrayList<LibraSummary.IsotopicContributions.ContributingChannel.AffectedChannel>();
                }
                return this.affectedChannel;
            }

            /**
             * Gets the value of the channel property.
             * 
             */
            public long getChannel() {
                return channel;
            }

            /**
             * Sets the value of the channel property.
             * 
             */
            public void setChannel(long value) {
                this.channel = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="channel" use="required" type="{http://regis-web.systemsbiology.net/protXML}positiveInt" />
             *       &lt;attribute name="correction" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class AffectedChannel {

                @XmlAttribute(name = "channel", required = true)
                protected long channel;
                @XmlAttribute(name = "correction", required = true)
                @XmlJavaTypeAdapter(Adapter2 .class)
                @XmlSchemaType(name = "float")
                protected Float correction;

                /**
                 * Gets the value of the channel property.
                 * 
                 */
                public long getChannel() {
                    return channel;
                }

                /**
                 * Sets the value of the channel property.
                 * 
                 */
                public void setChannel(long value) {
                    this.channel = value;
                }

                /**
                 * Gets the value of the correction property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public Float getCorrection() {
                    return correction;
                }

                /**
                 * Sets the value of the correction property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCorrection(Float value) {
                    this.correction = value;
                }

            }

        }

    }

}
