//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 02:29:00 PM EDT 
//


package umich.ms.fileio.filetypes.protxml.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the umich.ms.fileio.filetypes.protxml.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: umich.ms.fileio.filetypes.protxml.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ASAPRatio }
     * 
     */
    public ASAPRatio createASAPRatio() {
        return new ASAPRatio();
    }

    /**
     * Create an instance of {@link LibraResult }
     * 
     */
    public LibraResult createLibraResult() {
        return new LibraResult();
    }

    /**
     * Create an instance of {@link ProteinprophetDetails }
     * 
     */
    public ProteinprophetDetails createProteinprophetDetails() {
        return new ProteinprophetDetails();
    }

    /**
     * Create an instance of {@link ProteinSummary }
     * 
     */
    public ProteinSummary createProteinSummary() {
        return new ProteinSummary();
    }

    /**
     * Create an instance of {@link LibraSummary }
     * 
     */
    public LibraSummary createLibraSummary() {
        return new LibraSummary();
    }

    /**
     * Create an instance of {@link LibraSummary.IsotopicContributions }
     * 
     */
    public LibraSummary.IsotopicContributions createLibraSummaryIsotopicContributions() {
        return new LibraSummary.IsotopicContributions();
    }

    /**
     * Create an instance of {@link LibraSummary.IsotopicContributions.ContributingChannel }
     * 
     */
    public LibraSummary.IsotopicContributions.ContributingChannel createLibraSummaryIsotopicContributionsContributingChannel() {
        return new LibraSummary.IsotopicContributions.ContributingChannel();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup }
     * 
     */
    public ProteinSummary.ProteinGroup createProteinSummaryProteinGroup() {
        return new ProteinSummary.ProteinGroup();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein createProteinSummaryProteinGroupProtein() {
        return new ProteinSummary.ProteinGroup.Protein();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein.Peptide }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein.Peptide createProteinSummaryProteinGroupProteinPeptide() {
        return new ProteinSummary.ProteinGroup.Protein.Peptide();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein.Peptide.IndistinguishablePeptide }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein.Peptide.IndistinguishablePeptide createProteinSummaryProteinGroupProteinPeptideIndistinguishablePeptide() {
        return new ProteinSummary.ProteinGroup.Protein.Peptide.IndistinguishablePeptide();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein.Peptide.IndistinguishablePeptide.ModificationInfo }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein.Peptide.IndistinguishablePeptide.ModificationInfo createProteinSummaryProteinGroupProteinPeptideIndistinguishablePeptideModificationInfo() {
        return new ProteinSummary.ProteinGroup.Protein.Peptide.IndistinguishablePeptide.ModificationInfo();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein.Peptide.ModificationInfo }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein.Peptide.ModificationInfo createProteinSummaryProteinGroupProteinPeptideModificationInfo() {
        return new ProteinSummary.ProteinGroup.Protein.Peptide.ModificationInfo();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein.IndistinguishableProtein }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein.IndistinguishableProtein createProteinSummaryProteinGroupProteinIndistinguishableProtein() {
        return new ProteinSummary.ProteinGroup.Protein.IndistinguishableProtein();
    }

    /**
     * Create an instance of {@link ProteinSummary.DatasetDerivation }
     * 
     */
    public ProteinSummary.DatasetDerivation createProteinSummaryDatasetDerivation() {
        return new ProteinSummary.DatasetDerivation();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinSummaryHeader }
     * 
     */
    public ProteinSummary.ProteinSummaryHeader createProteinSummaryProteinSummaryHeader() {
        return new ProteinSummary.ProteinSummaryHeader();
    }

    /**
     * Create an instance of {@link ProteinprophetDetails.NiInformation }
     * 
     */
    public ProteinprophetDetails.NiInformation createProteinprophetDetailsNiInformation() {
        return new ProteinprophetDetails.NiInformation();
    }

    /**
     * Create an instance of {@link ProteinprophetDetails.NspInformation }
     * 
     */
    public ProteinprophetDetails.NspInformation createProteinprophetDetailsNspInformation() {
        return new ProteinprophetDetails.NspInformation();
    }

    /**
     * Create an instance of {@link ASAPRatio.ASAPSeq }
     * 
     */
    public ASAPRatio.ASAPSeq createASAPRatioASAPSeq() {
        return new ASAPRatio.ASAPSeq();
    }

    /**
     * Create an instance of {@link ASAPRatio.ASAPSeq.ASAPPeak }
     * 
     */
    public ASAPRatio.ASAPSeq.ASAPPeak createASAPRatioASAPSeqASAPPeak() {
        return new ASAPRatio.ASAPSeq.ASAPPeak();
    }

    /**
     * Create an instance of {@link LibraResult.Intensity }
     * 
     */
    public LibraResult.Intensity createLibraResultIntensity() {
        return new LibraResult.Intensity();
    }

    /**
     * Create an instance of {@link XPressAnalysisSummary }
     * 
     */
    public XPressAnalysisSummary createXPressAnalysisSummary() {
        return new XPressAnalysisSummary();
    }

    /**
     * Create an instance of {@link ProteinprophetDetails.ProteinSummaryDataFilter }
     * 
     */
    public ProteinprophetDetails.ProteinSummaryDataFilter createProteinprophetDetailsProteinSummaryDataFilter() {
        return new ProteinprophetDetails.ProteinSummaryDataFilter();
    }

    /**
     * Create an instance of {@link ProteinSummary.AnalysisSummary }
     * 
     */
    public ProteinSummary.AnalysisSummary createProteinSummaryAnalysisSummary() {
        return new ProteinSummary.AnalysisSummary();
    }

    /**
     * Create an instance of {@link ASAPProtAnalysisSummary }
     * 
     */
    public ASAPProtAnalysisSummary createASAPProtAnalysisSummary() {
        return new ASAPProtAnalysisSummary();
    }

    /**
     * Create an instance of {@link LibraSummary.FragmentMasses }
     * 
     */
    public LibraSummary.FragmentMasses createLibraSummaryFragmentMasses() {
        return new LibraSummary.FragmentMasses();
    }

    /**
     * Create an instance of {@link ASAPPvalueAnalysisSummary }
     * 
     */
    public ASAPPvalueAnalysisSummary createASAPPvalueAnalysisSummary() {
        return new ASAPPvalueAnalysisSummary();
    }

    /**
     * Create an instance of {@link ASAPRatioPvalue }
     * 
     */
    public ASAPRatioPvalue createASAPRatioPvalue() {
        return new ASAPRatioPvalue();
    }

    /**
     * Create an instance of {@link NameValueType }
     * 
     */
    public NameValueType createNameValueType() {
        return new NameValueType();
    }

    /**
     * Create an instance of {@link LibraSummary.IsotopicContributions.ContributingChannel.AffectedChannel }
     * 
     */
    public LibraSummary.IsotopicContributions.ContributingChannel.AffectedChannel createLibraSummaryIsotopicContributionsContributingChannelAffectedChannel() {
        return new LibraSummary.IsotopicContributions.ContributingChannel.AffectedChannel();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein.AnalysisResult }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein.AnalysisResult createProteinSummaryProteinGroupProteinAnalysisResult() {
        return new ProteinSummary.ProteinGroup.Protein.AnalysisResult();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein.Annotation }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein.Annotation createProteinSummaryProteinGroupProteinAnnotation() {
        return new ProteinSummary.ProteinGroup.Protein.Annotation();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein.Peptide.PeptideParentProtein }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein.Peptide.PeptideParentProtein createProteinSummaryProteinGroupProteinPeptidePeptideParentProtein() {
        return new ProteinSummary.ProteinGroup.Protein.Peptide.PeptideParentProtein();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein.Peptide.IndistinguishablePeptide.ModificationInfo.ModAminoacidMass }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein.Peptide.IndistinguishablePeptide.ModificationInfo.ModAminoacidMass createProteinSummaryProteinGroupProteinPeptideIndistinguishablePeptideModificationInfoModAminoacidMass() {
        return new ProteinSummary.ProteinGroup.Protein.Peptide.IndistinguishablePeptide.ModificationInfo.ModAminoacidMass();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein.Peptide.ModificationInfo.ModAminoacidMass }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein.Peptide.ModificationInfo.ModAminoacidMass createProteinSummaryProteinGroupProteinPeptideModificationInfoModAminoacidMass() {
        return new ProteinSummary.ProteinGroup.Protein.Peptide.ModificationInfo.ModAminoacidMass();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinGroup.Protein.IndistinguishableProtein.Annotation }
     * 
     */
    public ProteinSummary.ProteinGroup.Protein.IndistinguishableProtein.Annotation createProteinSummaryProteinGroupProteinIndistinguishableProteinAnnotation() {
        return new ProteinSummary.ProteinGroup.Protein.IndistinguishableProtein.Annotation();
    }

    /**
     * Create an instance of {@link ProteinSummary.DatasetDerivation.DataFilter }
     * 
     */
    public ProteinSummary.DatasetDerivation.DataFilter createProteinSummaryDatasetDerivationDataFilter() {
        return new ProteinSummary.DatasetDerivation.DataFilter();
    }

    /**
     * Create an instance of {@link ProteinSummary.ProteinSummaryHeader.ProgramDetails }
     * 
     */
    public ProteinSummary.ProteinSummaryHeader.ProgramDetails createProteinSummaryProteinSummaryHeaderProgramDetails() {
        return new ProteinSummary.ProteinSummaryHeader.ProgramDetails();
    }

    /**
     * Create an instance of {@link ProteinprophetDetails.NiInformation.NiDistribution }
     * 
     */
    public ProteinprophetDetails.NiInformation.NiDistribution createProteinprophetDetailsNiInformationNiDistribution() {
        return new ProteinprophetDetails.NiInformation.NiDistribution();
    }

    /**
     * Create an instance of {@link ProteinprophetDetails.NspInformation.NspDistribution }
     * 
     */
    public ProteinprophetDetails.NspInformation.NspDistribution createProteinprophetDetailsNspInformationNspDistribution() {
        return new ProteinprophetDetails.NspInformation.NspDistribution();
    }

    /**
     * Create an instance of {@link ASAPRatio.ASAPSeq.ASAPPeak.ASAPDta }
     * 
     */
    public ASAPRatio.ASAPSeq.ASAPPeak.ASAPDta createASAPRatioASAPSeqASAPPeakASAPDta() {
        return new ASAPRatio.ASAPSeq.ASAPPeak.ASAPDta();
    }

}
