//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 02:29:00 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://regis-web.systemsbiology.net/protXML", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package umich.ms.fileio.filetypes.protxml.jaxb;
