//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.11 at 10:24:01 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://regis-web.systemsbiology.net/protXML", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package umich.ms.fileio.filetypes.protxml.jaxb.standard;
