//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.20 at 02:40:52 PM EDT 
//


package umich.ms.fileio.filetypes.agilent.cef.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the umich.ms.fileio.filetypes.agilent.cef.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: umich.ms.fileio.filetypes.agilent.cef.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MSPeaks }
     * 
     */
    public MSPeaks createMSPeaks() {
        return new MSPeaks();
    }

    /**
     * Create an instance of {@link P }
     * 
     */
    public P createP() {
        return new P();
    }

    /**
     * Create an instance of {@link MSDetails }
     * 
     */
    public MSDetails createMSDetails() {
        return new MSDetails();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link CompoundList }
     * 
     */
    public CompoundList createCompoundList() {
        return new CompoundList();
    }

    /**
     * Create an instance of {@link Compound }
     * 
     */
    public Compound createCompound() {
        return new Compound();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Spectrum }
     * 
     */
    public Spectrum createSpectrum() {
        return new Spectrum();
    }

    /**
     * Create an instance of {@link RTRanges }
     * 
     */
    public RTRanges createRTRanges() {
        return new RTRanges();
    }

    /**
     * Create an instance of {@link RTRange }
     * 
     */
    public RTRange createRTRange() {
        return new RTRange();
    }

    /**
     * Create an instance of {@link CEF }
     * 
     */
    public CEF createCEF() {
        return new CEF();
    }

}
